services:
  postgres:
    image: postgres:16.10-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: nicolas
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: pulse_chat
    ports:
      - "5433:5432"
    volumes:
      - ./init/:/docker-entrypoint-initdb.d