# 伺服器設定，Grafana 會透過 3200 埠讀取資料
server:
  http_listen_port: 3200

# 分發器：負責接收從 Java 傳來的數據
distributor:
  receivers:
    otlp:
      protocols:
        grpc: # 注意：這裡只需寫 grpc:，不需要寫埠號，預設就是 4317 (Java預設)
        http: # 備用 (Port 4318)

# 緩衝區設定（開發環境使用預設即可）
ingester:
  max_block_duration: 5m

# 儲存設定：決定數據要存在哪裡
storage:
  trace:
    backend: local # 使用本地檔案儲存
    wal:
      path: /var/lib/tempo/wal # Write Ahead Log 路徑
    local:
      path: /var/lib/tempo/traces
